name: CI

on:
  pull_request_review:
    types: [submitted, edited]

  push:
    branches:
      - '*'

jobs:
  build-frontend:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create environment directory
        run: mkdir -p client/src/environments

      - name: Setup environment variables
        run: |
          echo $'${{ secrets.ENV_FILE_CONTENT }}' > client/src/environments/environment.ts
          echo $'${{ secrets.ENV_FILE_DEV_CONTENT }}' > client/src/environments/environment.development.ts

      - name: List environment files for debugging
        run: ls -al client/src/environments

      - name: Print environment.ts contents for debugging
        run: cat client/src/environments/environment.ts

      - name: Print environment.development.ts contents for debugging
        run: cat client/src/environments/environment.development.ts

      - name: Install dependencies
        run: |
          cd client
          npm install --force

      - name: Build frontend
        run: |
          cd client
          npm run build

  build-backend:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup environment variables
        run: echo "${{ secrets.BACKEND_ENV_FILE_CONTENT }}" > .env

      - name: Build backend
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests
